### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by silvioprog** [andrelmlins/svelte-dts#2]
Hi.

Consider the following steps:

```
C:\git>git clone https://github.com/duallsistemas/duall-svelte-bootstrap5.git
cd duall-svelte-bootstrap5/
npm i
npm i svelte-dts -D
npx svelte-dts -i src/index.js -o src/index.d.ts
```

it raises the following error:

```
C:\git\duall-svelte-bootstrap5>npx svelte-dts -i src/index.js -o src/index.d.ts
(node:15504) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at TypescriptTransformer.toString (C:\git\duall-svelte-bootstrap5\node_modules\svelte-dts\dist\transformer\typescript.js:61:14)
    at TypescriptTransformer.<anonymous> (C:\git\duall-svelte-bootstrap5\node_modules\svelte-dts\dist\transformer\typescript.js:72:55)
    at Generator.next (<anonymous>)
    at C:\git\duall-svelte-bootstrap5\node_modules\svelte-dts\dist\transformer\typescript.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\git\duall-svelte-bootstrap5\node_modules\svelte-dts\dist\transformer\typescript.js:23:12)
    at TypescriptTransformer.appendFile (C:\git\duall-svelte-bootstrap5\node_modules\svelte-dts\dist\transformer\typescript.js:70:16)
    at C:\git\duall-svelte-bootstrap5\node_modules\svelte-dts\dist\generator.js:111:70
    at Array.map (<anonymous>)
    at Generator.<anonymous> (C:\git\duall-svelte-bootstrap5\node_modules\svelte-dts\dist\generator.js:111:49)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is this a bug, or I'm doing something wrong? 😕

TIA for any help!

**Comment by silvioprog** [comment]
Problem solved after renaming the file from `types.d.ts` to `types.ts` in my repository! 😅
